name: 🚀 Deploy website on push

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v3

    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 104.234.134.10
        username: main@zsasocks.com
        password: ${{ secrets.ftp_password_2 }}
        protocol: ftps
        port: 21
        timeout: 1200000
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
      env:
        GIT_TRACE: 1
