name: Publish Website to CPanel
on:
  push:
    branches:
      - develop
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.1.0
        with:
          fetch-depth: 2 

      # Optional: Install PHP and Composer (if needed)
      - name: Install PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
            php-version: '8.1' # Adjust to match your PHP version
            tools: 'composer'

      - name: Install PHP dependencies
        run: composer update --no-dev --optimize-autoloader

      # Sync files using FTP-Deploy-Action
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ftp.zsasocks.com
          username: zsasocks
          password: ${{ secrets.ftp_password }}
          protocol: ftps
          port: 21
          security: loose
          server-dir: /public_html/ # Target directory on server


